DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS SHOWING;
DROP TABLE IF EXISTS SEAT;
DROP TABLE IF EXISTS MOVIE_GENRE;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS HALL;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE HALL
(
	hall_id SERIAL PRIMARY KEY,
	name_hall VARCHAR(10) UNIQUE NOT NULL,
	type_hall VARCHAR(15) NOT NULL
);

CREATE TABLE CUSTOMER
(
	customer_id SERIAL PRIMARY KEY,
	full_name VARCHAR(100) NOT NULL,
	email_address VARCHAR(100) UNIQUE NOT NULL,
	phone_number VARCHAR(15) NOT NULL
);

CREATE TABLE GENRE
(
	genre_id SERIAL PRIMARY KEY,
	genre_name VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE MOVIE
(
	movie_id SERIAL PRIMARY KEY,
	title VARCHAR(40) NOT NULL,
	release_date DATE NOT NULL,
	duration INTEGER NOT NULL CHECK(duration > 0)
);

CREATE TABLE MOVIE_GENRE
(
	movie_id INTEGER NOT NULL REFERENCES MOVIE(movie_id) ON DELETE CASCADE,
	genre_id INTEGER NOT NULL REFERENCES GENRE(genre_id) ON DELETE CASCADE,
	PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE SHOWING
(
	session_id SERIAL PRIMARY KEY,
	movie_id INTEGER NOT NULL REFERENCES MOVIE(movie_id),
	hall_id INTEGER NOT NULL REFERENCES HALL(hall_id),
	start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
	CONSTRAINT UQ_HallTime UNIQUE (hall_id, start_time)
);

CREATE TABLE SEAT
(
	seat_id SERIAL PRIMARY KEY,
	hall_id INTEGER NOT NULL REFERENCES HALL(hall_id),
	row_num INTEGER NOT NULL CHECK(row_num > 0),
	seat_number INTEGER NOT NULL CHECK(seat_number >0),
	CONSTRAINT UQ_SeatLocation UNIQUE (hall_id, row_num, seat_number)
);

CREATE TABLE BOOKING
(
	booking_id  SERIAL PRIMARY KEY,
	customer_id INTEGER NOT NULL REFERENCES CUSTOMER(customer_id),
	booking_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	total_amount NUMERIC(8,2) NOT NULL CHECK (total_amount >= 0)
);

CREATE TABLE TICKET
(
	ticket_id SERIAL PRIMARY KEY,
	booking_id INTEGER NOT NULL REFERENCES BOOKING(booking_id),
	session_id INTEGER NOT NULL REFERENCES SHOWING(session_id),
	seat_id INTEGER NOT NULL REFERENCES SEAT(seat_id),
	price NUMERIC (6,2) NOT NULL CHECK (price > 0),
	CONSTRAINT UQ_Ticket UNIQUE (session_id, seat_id)
);
