SELECT 'CUSTOMER' as таблиця, COUNT(*) as записів FROM CUSTOMER
UNION ALL SELECT 'HALL', COUNT(*) FROM HALL
UNION ALL SELECT 'MOVIE', COUNT(*) FROM MOVIE
UNION ALL SELECT 'SEAT', COUNT(*) FROM SEAT
UNION ALL SELECT 'SESSION', COUNT(*) FROM SHOWING
UNION ALL SELECT 'BOOKING', COUNT(*) FROM BOOKING
UNION ALL SELECT 'TICKET', COUNT(*) FROM TICKET;

